FROM node:20.13-alpine

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

# set the environment variable
RUN echo "VITE_API_URL=${API_URL}" >> .env

RUN npm run build

EXPOSE 3000

CMD [ "npm", "run", "preview" ]