version: '3.2'
services:
  mysqldb:
    image: mysql:8.4
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3308:3306'
    networks:
      - carex-mysql-net
    expose:
      # Opens port 3306 on the container
      - '3308'
    environment:
      MYSQL_DATABASE: carex
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - carex-mysql:/var/lib/mysql
  # carex-ml:
  #   image: python:3.12.3-slim
  #   container_name: carex-ml
  #   volumes:
  #     - ./ml:/app
  #     - python-packages:/usr/local/lib/python3.10/site-packages
  #   working_dir: /app
  #   command: bash -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
  #   networks:
  #     - carex-mysql-net
  #   depends_on:
  #     - mysqldb
  #   ports:
  #     - '8001:8000'
  carex-api:
    image: maven:3.8.3-openjdk-17-slim
    container_name: carex-api
    volumes:
      - ./server:/app
    working_dir: /app
    command: bash -c "mvn clean install -DskipTests && mvn spring-boot:run"
    networks:
      - carex-mysql-net
    depends_on:
      - mysqldb
    ports:
      - '8000:8080'
    expose:
      - '25'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/carex?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_SERVER_PORT: '8080'
  carex-web:
    image: node:20.13-slim
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: bash -c "npm install && npm i -g next && npm run dev -- --host 0.0.0.0 --port 3000"
    ports:
      - "3000:3000"
    expose:
      - '3000'
    environment:
      VITE_PUBLIC_API_URL: ${API_URL}

networks:
  carex-mysql-net:


volumes:
  carex-mysql:
    external: true
  maven-repo:
    external: true