version: '3.3'
services:
  mysqldb:
    image: mysql:8.4
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3308:3306'
    networks:
      - carex-mysql-net
    expose:
      # Opens port 3306 on the container
      - '3308'
    environment:
      MYSQL_DATABASE: carex
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - carex-mysql:/var/lib/mysql
  carex-api:
    image: maven:3.8.3-openjdk-17-slim
    container_name: carex-api
    working_dir: /app
    command: bash -c "mvn clean install -DskipTests && mvn spring-boot:run"
    networks:
      - carex-mysql-net
    depends_on:
      - mysqldb
    ports:
      - '8000:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/carex?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_PROFILES_ACTIVE: prd
      MAIL_USERNAME: ${MAIL_USERNAME}
      MYSQL_PASSWORD: ${MAIL_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SERVER_PORT: '8080'
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
networks:
  carex-mysql-net:

volumes:
  carex-mysql:
    external: true