version: '3.2'
services:
  mysqldb:
    image: mysql:8.4
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3308:3306'
    networks:
      - carex-mysql-net
    expose:
      # Opens port 3306 on the container
      - '3308'
    environment:
      MYSQL_DATABASE: carex
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - carex-mysql:/var/lib/mysql
  carex-ml:
    build:
      context: ./ml
      dockerfile: Dockerfile
    container_name: carex-ml
    volumes:
      - ./ml:/app
    ports:
      - '5050:5050'
    expose:
      - '5050'
  carex-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: carex-api
    volumes:
      - maven-repo:/root/.m2
    networks:
      - carex-mysql-net
    depends_on:
      - mysqldb
    ports:
      - '8000:8080'
    expose:
      - '8000'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/carex?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_SERVER_PORT: '8080'
      SPRING_PROFILES_ACTIVE: prd
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
  carex-web:
    container_name: carex-web
    restart: on-failure
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile-prd
    image: node:20.13-slim
    working_dir: /app
    command: bash -c "npm install && npm run build && npm run preview"
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    expose:
      - '3000'

networks:
  carex-mysql-net:


volumes:
  carex-mysql:
    external: true
  maven-repo:
    external: true