spring:
  datasource:
<<<<<<< HEAD
    url: jdbc:mysql://localhost:3306/carex
=======
    url: jdbc:mysql://localhost:3306/carex?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
>>>>>>> 76550d94e548d7d620b20f4431376b517fd5e895
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: '8080'

application:
  security:
    enabled: true
    ignore:
      paths: /swagger-ui,/v3/api-docs,/api/v1/auth
    jwt:
      secret-key: secret
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false