import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const apiUrl = process.env.REACT_APP_API_URL;

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <p>Base API URL: {apiUrl}</p> */}
        {children}
      </body>
    </html>
  );
}
