version: '3.1'
services:
  carex-app:
      image: carex-app
      build:
        context: .
        dockerfile: Dockerfile
      ports:
      - '8000:8080'
      networks:
      - carex-mysql-net
      depends_on:
      - mysqldb
      volumes:
        - maven-repo:/root/.m2
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/carex
        SPRING_DATASOURCE_USERNAME: dev
        SPRING_DATASOURCE_PASSWORD: root
        SPRING_SERVER_PORT: '8080'
  mysqldb:
    image: mysql:8.4
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3308:3306'
    expose:
      # Opens port 3306 on the container
      - '3308'
    networks:
        - carex-mysql-net
    environment:
      MYSQL_DATABASE: carex
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: root
    volumes:
      - carex-mysql:/var/lib/mysql

networks:
    carex-mysql-net:

volumes:
    carex-mysql:
    maven-repo: