version: '3.1'
services:
  maven:
    image: maven:3.8.3-openjdk-17-slim
    container_name: carex-maven
    volumes:
      - maven-repo:/root/.m2
      - .:/app
    working_dir: /app
    command: bash -c "mvn clean install -DskipTests && mvn spring-boot:run"
    networks:
        - carex-mysql-net
    depends_on:
      - mysqldb

    ports:
      - '8000:8080'
    expose:
      - '25'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/carex
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_SERVER_PORT: '8080'
  mysqldb:
    image: mysql:8.4
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3308:3306'
    expose:
      # Opens port 3306 on the container
      - '3308'
    networks:
        - carex-mysql-net
    environment:
      MYSQL_DATABASE: carex
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: root
    volumes:
      - carex-mysql:/var/lib/mysql

networks:
    carex-mysql-net:

volumes:
    carex-mysql:
      external: true
    maven-repo:
      external: true