import Login from "./Login";
import Signup from "./Signup";
import HomePage from "./HomePage";
import Workshop from "./Workshop";
import Yoga from "./Yoga";
import EditProfile from "./EditProfile";
import ChoosePlan from "./ChoosePlan";
import Notifications from "./Notifications";
import PasswordAndSecurity from "./PasswordAndSecurity";
import Calories from "./Calories";
import BMIResult from "./BMIResult";
export { Login, Signup, HomePage, Workshop, Yoga, EditProfile, ChoosePlan, Notifications, PasswordAndSecurity, Calories, BMIResult};
